keepassxreboot/keepassxc-org

- download.html
- update Fedora to official package
- separate Fedora and CentOS
- add install command line to all official packages
- remove plural from some instances of "packages"
No sudo was used for the examples but instead a hash to indicate root shell as sudo is not necessarily universally available and configured - can be changed to sudo if seen otherwise.
> Improve Linux downloads

- docs.html
- download.html
I noticed that y'all [recently replaced "OS X" with the current name "macOS" on the project page](https://github.com/keepassxreboot/keepassxreboot.github.io/commit/60e1cb2e56a2b63b735a89d267bc34bfc96867f1), so I thought I'd so the same for Downloads and Docs pages. (Note that "macOS" is used on [the Screenshots page](https://keepassxc.org/screenshots) already.)
> Rename 'OS X' to 'macOS' on the Project and Docs pages

- download.html
I think/hope this fixes this issue: https://github.com/keepassxreboot/keepassxc/issues/1449
There could be other links on the site broken in the same way-- don't have extra time to check at the moment, unfortunately.
> Fixes some internal website links

- docs/index.html
- project.html
Here are the changes related to the new browser extension. Some info about the legacy browser integration also added. The new wiki page docs/keepassxc-browser-migration.md is already added.
> Browser extension related changes

- docs/index.html
- project.html
Updates the URL's. The current URL's in the web page are old ones. Those links are already visible at keepassxc.org so this needs to be merged ASAP.
> Update extension and browser migration document URL

- docs/index.html
Errors from the agent are common with non-OpenSSH agents. 2.3.2 will have more helpful error messages.
> Add entries for SSH Agent errors

- docs/index.html
Adds a link to the KeePassXC-Browser troubleshooting guide wiki page.
> Add troubleshooting guide link

- verifying-signatures.html
Since macOS users will have downloaded a `.DMG` file, their command to verify it is slightly different than Linux users. This commit splits these two sections, so Mac has its own, with the command being `$ gpg --verify KeePassXC-*.dmg.sig`. I tried this on my Mac and it works. 
Also, the output is similar if not identical to the Linux output, so I just copied that over.
> Command for verifying signature of macOS file is slightly different

- docs/index.html
The previous link "https://keepassxc.org/docs/keepassxc-browser-migration/" is currently returning 404. From my findings, the right location would now be
```
https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_configure_keepassxc_browser/
```
> Fixed FAQ dead link for Browser Integration docs

- _includes/navbar.html
- blog/_posts/2017-10-25-ubuntu-ppa.md
- blog/_posts/2017-12-14-2.2.4-released.md
- blog/_posts/2018-01-19-2.3-translations.md
- blog/_posts/2018-02-22-2.3-beta1-release.md
- blog/_posts/2018-02-28-2.3-released.md
- blog/_posts/2018-03-07-2.3.1-released.md
- blog/_posts/2018-05-08-2.3.2-released.md
- blog/_posts/2018-05-09-2.3.3-released.md
- blog/_posts/2018-08-23-2.3.4-released.md
- blog/_posts/2019-03-19-2.4.0-released.md
- blog/_posts/2019-04-13-2.4.1-released.md
- blog/_posts/2019-05-31-2.4.2-released.md
- blog/_posts/2019-06-11-2.4.3-released.md
- blog/_posts/2019-10-26-2.5.0-released.md
- blog/_posts/2019-11-11-2.5.1-released.md
- blog/_posts/2020-01-04-2.5.2-released.md
- blog/_posts/2020-01-19-2.5.3-released.md
- blog/_posts/2020-04-09-2.5.4-released.md
- blog/_posts/2020-07-07-2.6.0-released.md
- blog/_posts/2020-08-19-2.6.1-released.md
- blog/_posts/2020-10-21-2.6.2-released.md
- blog/index.html
- index.html
Hi!
I read the 2.6.2 release announcement in my RSS feed reader (I use inoreader.com). It looked a bit interesting to see that Chrome was warning about a Flash Player being included.
I took a look and saw that the KeePassXC logo svg file was being included with the `<object>` tag, and my feed reader is not including all of the attributes for whatever reason. But apparently the object tag is not really necessary for svg images these days. https://stackoverflow.com/questions/4476526/do-i-use-img-object-or-embed-for-svg-files
So I wanted to see if I could improve it. Unfortunately, I do not think just changing it to `<img>` will be very good for most feed readers since the CSS stylesheet from the website isn't included (I don't think there's a good way to include it either). It would look …
> Tweak the blog teaser image

- download.html
A quick PR to change the Homebrew cask upgrade for [the `2.6.0` upgrade](https://brew.sh/2020/12/01/homebrew-2.6.0/):
> All `brew cask` commands have been deprecated in favour of `brew` commands (with `--cask`) when necessary
> Upgrade cask installation command for brew 2.6.0

- blog/feed.xml
The `self` link of the feed points to https://keepassxc.org/feed.xml which results in a 404.
> fix blog atom feed 'self' url

- download.html
This inserts the recently added folder structure from the winget-pkgs manifest repository. 
The manifests are now grouped into subfolders named by the initial letters of the contained projects.
The KeePassXCTeam manifests therefore moved into the subfolder `k`.
Fixes #91
> Update link of winget-pkgs manifests to new structure

- docs/index.html
Previously Windows' own OpenSSH option was not mentioned, even though KeePassXC supports it.
Additionally, to better differentiate between the two major platforms (Unix vs. Window) and their differences they now each have a separate section.
Some additional comments:
I removed the line following line from the `Why is Pageant refusing my keys?`-question:
> There doesn't seem to be any alternative to Pageant for Windows that supports both of them.
Because from a cursorily glance at the [Win32 OpenSSH issues](https://github.com/PowerShell/Win32-OpenSSH/issues?q=is%3Aissue+askpass) there may be options to correctly provide and configure `SSH_ASKPASS` when using Windows' own OpenSSH binaries. I haven't verified that.
There is "a lot" of duplication between the two sections – yeah, that's true. …
> Update SSH Agent FAQ for Windows

- download.html
`sudo` is not required when installing a flatpak application using the
`--user` flag. I think we should recommend that by default.
> Use --user flag for flatpak install

- _data/version.yml
Advertise v. 2.7.1 Stable for Flatpak on Linux.
> Update version.yml (Flatpak)

- download.html
Trying to install it with winget, you should point to the package from winget repository, not the windows store one (which has a separate link).
```
PS C:\Users\filip>  winget install keepassxc
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").
Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
Multiple packages found matching input criteria. Please refine the input.
Name      Id                      Source
-----------------------------------------
KeePassXC XP8K2L36VP0QMB          msstore
KeePassXC KeePassXCTeam.KeePassXC winget
PS …
```
> Point winget to more specific package

- index.html
I think having the link only in the top right corner is easy to miss.
> Added link to repo in paragraph

- content/docs/index.html
- fixes 404 error when navigating to Project section from FAQ
- fixes incorrect section anchor to OpenSSH agent and Pageant on Windows in the User Guide
> FAQ: fix incorrect anchors to sections

- layouts/download/single.html
The `community` repository was recently merged into `extra`. [Source](https://archlinux.org/news/git-migration-announcement/)
> Update link for the official Arch Linux package

- layouts/download/single.html
There are no instructions on how to set up the flathub remote. Earlier, [the flatpak setup instructions](https://flatpak.org/setup/Debian) were enough, but in https://github.com/keepassxreboot/keepassxc-org/pull/99 the `--user` flag was added which requires the user to also set up their flathub remote using the `--user` flag. This was not obvious to me and it took me a few minutes for me to understand why I was getting the error `error: No remote refs found for ‘flathub’`.
I think explicitly telling the user how to add the flathub remote will help a lot of users.
> Add `flatpak remote-add` command to instructions

- content/docs/index.html
- adds reference to KeePassX's announcement of stopped development
- clarifies the database formats entry
- a few additional minor language improvements and cleanups
> FAQ: update KeePassX and file format entries

- layouts/download/single.html
Closes #123 
- Fixes alt text for the browser logos in the existing "Next step" sequence
- Fixes the offset button text at smaller breakpoints by switching to flexbox and using `gap` instead of `margin`.
- Adds a tab with links to download the browser extensions and their source code alongside the other downloads on the site
> Adds a tab for the browser extensions on the downloads page

- content/docs/index.html
KeePassHTTP support has been removed a few years ago. Most places in the docs seem to have been updated, but the FAQ still talked about it as a supported browser integration. I think the wording could be improved, edits/suggestions are welcome :)
> Remove mentions of KeePassHTTP from FAQ

- assets/scss/noscript.scss
- assets/scss/theme/_global.scss
- layouts/_default/baseof.html
- layouts/download/single.html
- package-lock.json
- package.json
As KeePassXC is a security tool, I think it is important for the website to work well when JavaScript is disabled. The current state is that the Downloads page is completely unusable. With these tweaks it works pretty good. The collapsible sections now work completely without using any JavaScript, using `<details>` and `<summary>`.
I'm also fixing a few unrelated small issues, see the commit messages for detailed information on each change. I'm willing to split these out to separate PRs if you prefer, just let me know.
You may want to review with whitespace changes omitted, since a lot of the changes is pure indenting.
There's still some minor UI discrepancies when JavaScript is disabled, but I don't know uikit well enough to fix them without more research. As a test I did try and copy …
> Update the Downloads page to work without JavaScript

- layouts/_default/baseof.html
**Setup**
```
jtorres@MacBookAir keepassxc-org % hugo version
hugo v0.147.0+extended+withdeploy darwin/arm64 BuildDate=2025-04-25T15:26:28Z VendorInfo=brew
jtorres@MacBookAir keepassxc-org % 
jtorres@MacBookAir keepassxc-org % npm list
keepassxc.org@1.0.0 /Users/jtorres/GitProjects/keepassxc-org
├── @fortawesome/fontawesome-free@6.7.1
├── jquery@3.7.1
├── ua-parser-js@2.0.0
└── uikit@3.21.16
```
**Details**
On recent versions of Hugo (such as v0.147.0), the site fails to build due to the following deprecation error:
ERROR deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and subsequently removed. Use css.Sass instead.
Full log:
```
jtorres@MacBookAir keepassxc-org % hugo      
Start building sites … 
hugo v0.147.0+extended+withdeploy darwin/arm64 BuildDate=2025-04-25T15:26:28Z …
```
> Replace resources.ToCSS with css.Sass due to deprecation

- content/docs/index.html
Looking at the docs after the merge of #143, realized that "Why would I use a password Manager" and "Who should use this" shared the same anchor ID's (making linking to one or the other not work as expected)
> make the "who should use this" faq have it's own anchor id

- content/docs/index.html
This fixes the "Setup Browser Integration" link (Docs/FAQ), which currently points to id "#_setup_browser_integration". The "KeePassXC_GettingStarted" document has an id of "#_browser_integration" for this section.
> Fix browser integration link id

- assets/scss/theme/_global.scss
- layouts/download/single.html
Promote the Flatpak distribution for Linux installs. Adjust a few other things on the download page and also fix a minor Hugo warning.
> Promote Flatpak Distribution for Linux
