download.html
I believe this resolves issue #5
=> :bug: Swap the hashes for the Windows downloads

project.html
Streamline the features list with the projects README.
=> Add Yubikey 2FA support to the features list

verifying-signatures.html
After a first read of this page I felt it left a lot of things under-explained, particularly for people not versed in this stuff. So I've tried to clarify things, mostly following the existing structure. It's longer but hopefully clearer.
One thing that bothers me about the text is the ordering - talking (a lot) about verification and then just mentioning integrity checking. Since the latter is a much simpler check, perhaps it should be discussed  first? That clears the way for describing about the more thorough verification check.
I started by branching from master but then rebased onto develop - is that correct? The contribution notes are a little vague about which branch you want things based on...
=> Rework of verifying-signatures.html (RFC)

download.html
Unofficial packages kept for current releases.
=> Add persistent link to downstream Debian package

download.html
Add [Homebrew Cask](https://github.com/caskroom/homebrew-cask) package to macOS download page.
=> Add Homebrew Cask

docs/index.html
Resolves https://github.com/keepassxreboot/keepassxc/issues/1577.
=> Add documentation for migrating to KDBX 4

docs/index.html
Initial FAQ entries for SSH Agent. Not grammar checked so please if someone could read it through with thought before merging.
=> SSH Agent FAQ

docs/index.html
Adds info about Firefox ESR limitations with WebExtension API.
=> Added Firefox ESR info text to Browser FAQ

docs/index.html
=> both projects are active

docs/index.html
Fix the troubleshooting link. Used a wrong syntax.
=> Fix the link

blog/_posts/2019-03-19-2.4.0-released.md
Let's make it easier for everyone to find more details of every single improvement or bug fix.
=> Link to GitHub issues/pull requests from 2.4.0 release notes

download.html
Hi there, thanks for this project!
Just a quick PR to add [the Chocolatey package](https://chocolatey.org/packages/keepassxc) as a download source for Windows (similar to Homebrew on macOS).
=> Add Chocolatey download source

download.html
=> Fix Windows download layout

docs/index.html
There are probably technical incorrections I've introduced - feel free to suggest changes
(@PhilippC you're definitely qualified for this :D )
Also, there're probably some sentences you'd like to change - feel free:)
Fixes https://github.com/keepassxreboot/keepassxreboot.github.io/issues/61, improves https://github.com/keepassxreboot/keepassxc/issues/1060
This is how the q&a looks like after the change:
=> Improve Q&A's `Does KeePassXC work on mobile phones?`

docs/index.html
=> faq: add instructions on string fields

docs/index.html
> I'm getting a "Too many authentication failures" error, what shall I do?
=> Add SSH agent FAQ entry: I'm getting a "Too many authentication failures" error, what shall I do?

download.html
Add Windows Package Manager information at the Windows download page.
=> add Windows Package Manager Package

donate.html
=> Update Crypto wallet addresses

docs/index.html
The Question only lists 2 platforms, but the answer speaks about 3 platforms.
=> Add Linux to Auto-Type FAQ

content/docs/index.html
Suggested wording to fix #125. I'm sure the wording can be improved!
=> Update FAQ re: Wayland

layouts/download/single.html
=> Update Flathub repo url
